Update apple-appstore-deployment.md
FlutterFlow/flutterflow-documentation pull request #122
Opened 2024-08-21 19:56 UTC by graybright

Added step for first time key deployment (need to click Integrations on tab bar, this page will then display the Request Access button.

### Description
Provide a brief overview of what this documentation update is about. Explain what sections or topics are being added or revised.

Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-XXX  

## Type of change
- [ ] Typo fix 
- [ ] New feature 
- [ ] Enhancement to current docs
- [ ] Removed outdated references
- [ ] Update assets

2024-08-23 13:28 UTC, PoojaB26 requested changes

2024-08-23 13:28 UTC, PoojaB26 commented on docs/testing-deployment-publishing/publishing/apple-appstore-deployment.md
> +*INSERT NEW INFOMATION HERE* If you haven't added a key before, click 'Integrations' and you will see 'request access'. For further details, view FlutterFlow Video here> https://youtu.be/L2BpgVog4so?
Hi @graybright, 

Thank you for submitting this PR! However, this is not formatted correctly, I see an extra text that is unnecessary and youtube video link is not properly formatted. 
And if you want to add such extra notes or info, please use Admonitions which is a way to add special callouts. 

Read more about it on our [Contribution Guidelines](https://github.com/FlutterFlow/flutterflow-documentation?tab=readme-ov-file#contribution-guidelines).

2024-09-26 15:05 UTC, leighajarett commented
@PoojaB26 can you just make your suggested changes and merge this in?

2024-10-03 08:45 UTC, PoojaB26 commented on docs/testing-deployment-publishing/publishing/apple-appstore-deployment.md
> +*INSERT NEW INFOMATION HERE* If you haven't added a key before, click 'Integrations' and you will see 'request access'. For further details, view FlutterFlow Video here> https://youtu.be/L2BpgVog4so?
```suggestion
:::info
If you haven't added a key before, click 'Integrations' and you will see 'Request Access'. For further details, watch a [demo](https://youtu.be/L2BpgVog4so?si=yS9r_PBeORgd6Uhp&t=240) here. 
```

2024-10-03 08:45 UTC, PoojaB26 approved these changes

2024-10-03 08:49 UTC, merged