Widget builder as parameter
FlutterFlow/flutterflow-documentation pull request #142
Opened 2024-09-19 10:46 UTC by pinkeshmars

### Widget builder as parameter

[Linear ticket](https://linear.app/flutterflow/issue/DEVR-601/docs-widget-builder-as-a-parameter) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-601 

## Type of change
- [ ] Typo fix 
- [x] New feature 
- [ ] Enhancement to current docs
- [ ] Removed outdated references
- [ ] Update assets

2024-09-23 11:04 UTC, PoojaB26 requested changes
Minor changes needed.

2024-09-23 11:04 UTC, PoojaB26 commented on docs/resources/ui/components/using-components.md
> +2. Then, add the widget builder placeholder to the appropriate location within the component’s widget tree.
Use the suggestion or modify slightly if you feel so.

2024-09-24 10:37 UTC, pinkeshmars commented on docs/resources/ui/components/using-components.md
> +The Widget Builder as Parameter feature allows you to create flexible and reusable UI components by passing widgets as parameters. This helps maintain a consistent design while allowing for customiza
Good point! updated.

2024-09-24 10:37 UTC, pinkeshmars commented on docs/resources/ui/components/using-components.md
> +For example, say you’re building a custom dropdown component that displays a list of items. The structure of the dropdown remains the same, but the style and content of the dropdown items might diffe
Updated!

2024-09-24 10:38 UTC, pinkeshmars commented on docs/resources/ui/components/using-components.md
> +Let’s see how to use this feature with an example from an eComm app. On the shipping address page, you can maintain a consistent style and layout for input fields while allowing customization for the
Done!

2024-09-24 10:38 UTC, pinkeshmars commented on docs/resources/ui/components/using-components.md
> +![widget-builder-as-parameter-example.avif](imgs/widget-builder-as-parameter-example.avif)
ok, updated!

2024-09-24 10:38 UTC, pinkeshmars commented on docs/resources/ui/components/using-components.md
> +1. If you haven't already, start by creating a new component. Next, define a parameter and set its type to **Widget Builder**. To [pass data from the current component to the widget builder](#pass-pa
Used your suggestion!

2024-09-24 10:38 UTC, pinkeshmars commented on docs/resources/ui/components/using-components.md
> +2. Then, add the widget builder placeholder to the appropriate location within the component’s widget tree.
Changed it slightly.

2024-09-24 10:39 UTC, pinkeshmars commented
Hey @PoojaB26, all review comments are addressed now. Could you please check?

2024-09-24 11:05 UTC, PoojaB26 approved these changes
LGTM! Thanks for working on the changes!

2024-09-24 11:05 UTC, merged