Added On Dispose Info
FlutterFlow/flutterflow-documentation pull request #228
Opened 2024-12-11 11:10 UTC by pinkeshmars

### Description
Added On Dispose Info

[Linear ticket](https://linear.app/flutterflow/issue/DEVR-715/[docs]-ondispose-action-trigger) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-715 

## Type of change
- [ ] Typo fix 
- [x] New feature 
- [ ] Enhancement to current docs
- [ ] Removed outdated references
- [ ] Update assets

2024-12-11 15:06 UTC, PoojaB26 requested changes
Some of the examples dont work for FlutterFlow because if the creation of them is not allowed in FF, the disposal of them wont make sense to users. We must remember the distinction between Flutter and FlutterFlow in such examples so we dont confuse the users.

2024-12-11 15:06 UTC, PoojaB26 commented on docs/resources/ui/pages/page-lifecycle.md
> +- **Cleaning Up Resources:** Use this action trigger to cancel timers, close database connections, or unsubscribe from streams to prevent memory leaks and unnecessary processing.
Only first example makes sense. The rest are in relation to Flutter.

2024-12-12 12:08 UTC, pinkeshmars commented
@PoojaB26 you can take a look again.

2024-12-12 12:16 UTC, PoojaB26 approved these changes
Typo fix required. Thanks for working on these fixes!

2024-12-12 12:16 UTC, PoojaB26 commented on docs/resources/ui/components/component-lifecycle.md
> +Imagine a scenario where a [periodic action](../../../resources/control-flow/time-based-logic/periodic-action.md), such as fetching live weather updates, is started in a component when it is loaded (
```suggestion
Imagine a scenario where a [periodic action](../../../resources/control-flow/time-based-logic/periodic-action.md), such as fetching live weather updates, is started in a component when it is loaded (i.e, [On Initialization](#on-initialization-action-trigger)). The action runs periodically, providing real-time data updates as long as the component is active. However, when the page containing the component is navigated away, you need to stop the periodic action to conserve resources and prevent unnecessary processing. By using the On Dispose action trigger, you can safely stop the periodic updates and clean up any associated resources.
```

2024-12-12 18:17 UTC, merged