actions overview/concepts page
FlutterFlow/flutterflow-documentation pull request #24
Opened 2024-05-10 21:07 UTC by johnbhiggins7

### Description
- Added Actions Overview/Concepts page

Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-XXX  

## Type of change
- [ ] Typo fix 
- [x] New feature 
- [ ] Removed outdated references

2024-05-13 23:48 UTC, leighajarett commented on docs/resources/action-flow-editor/overview.md
> +Both Triggers and Actions are just functions. Triggers are functions executed when a user performs a specific interaction, while Actions are functions executed in response to the triggered event. Com
```suggestion
Triggers represent a specific event, while Actions are functions executed in response to the triggered event. Common triggers are:
```

I know triggers are technically callback functions, but I think that might be a bit more detail than is necessary?

2024-05-13 23:50 UTC, leighajarett commented on docs/resources/action-flow-editor/overview.md
> +The Action Flow Editor is a visual, node-based editor used to define the functions for Triggers and Actions. This editor simplifies the process of creating and managing business logic.
"define the functions for Triggers and Actions" --> "configure the functions that run in response to a trigger"?

2024-05-13 23:54 UTC, PoojaB26 commented
Hey @johnbhiggins7 Can we have all the changes mentioned in this [ticket](https://linear.app/flutterflow/issue/DEVR-315/user-interactivity-actions) and then we can review the changes together? It helps us know if we need to move things around to different sections and how the section looks in overall. Can we make this PR a draft till all the changes are available in this PR? Thanks.

2024-05-14 00:02 UTC, leighajarett commented on docs/resources/action-flow-editor/overview.md
> +tags: []
Might be useful to add something about action output variables?

2024-05-14 00:05 UTC, leighajarett requested changes
Few small comments

2024-06-01 04:11 UTC, closed without merging